TRUNCATE TABLE `bawaan`;
TRUNCATE TABLE `bawaanayam`;
TRUNCATE TABLE `bawaanbarang`;
TRUNCATE TABLE `bawaanproduk`;
TRUNCATE TABLE `belanja`;
TRUNCATE TABLE `belanjaayam`;
TRUNCATE TABLE `belanjadetail`;
TRUNCATE TABLE `cashflow`;
TRUNCATE TABLE `pemasukan`;
TRUNCATE TABLE `pengeluaran`;
TRUNCATE TABLE `pengeluarandetail`;
TRUNCATE TABLE `pinjaman`;
TRUNCATE TABLE `produkoutlet`;
TRUNCATE TABLE `setoran`;
TRUNCATE TABLE `setoranpengeluaran`;
TRUNCATE TABLE `setoranpenjualan`;
TRUNCATE TABLE `setoransisabarang`;
TRUNCATE TABLE `setoransisaproduk`;
TRUNCATE TABLE `sirkulasibarang`;
TRUNCATE TABLE `sirkulasiayam`;
TRUNCATE TABLE `sirkulasiproduk`;
TRUNCATE TABLE `sirkulasibarangoutlet`;
TRUNCATE TABLE `sirkulasiayamoutlet`;
TRUNCATE TABLE `sirkulasiprodukoutlet`;
TRUNCATE TABLE `pemotongan`;
TRUNCATE TABLE `pemotongandetail`;
TRUNCATE TABLE `produkoutlet`;
TRUNCATE TABLE `ayamoutlet`;
TRUNCATE TABLE `barangoutlet`;
TRUNCATE TABLE `produksi`;
TRUNCATE TABLE `produksibarang`;
TRUNCATE TABLE `produksiproduk`;
TRUNCATE TABLE `produksiayam`;
TRUNCATE TABLE `internal`;
TRUNCATE TABLE `internalayam`;
TRUNCATE TABLE `internalbarang`;
TRUNCATE TABLE `internalproduk`;
TRUNCATE TABLE `cashflowoutlet`;
UPDATE `produk` SET stock = 0;
UPDATE `ayam` SET pcs = 0, kg = 0;
UPDATE `baranggudang` SET stock = 0;
UPDATE `debitur` SET saldo = 0;
UPDATE `outlet` SET saldo = 0;