TRUNCATE TABLE `bawaan`;
TRUNCATE TABLE `belanja`;
TRUNCATE TABLE `belanjaayam`;
TRUNCATE TABLE `belanjadetail`;
TRUNCATE TABLE `cashflow`;
TRUNCATE TABLE `pemasukan`;
TRUNCATE TABLE `pengeluaran`;
TRUNCATE TABLE `pengeluarandetail`;
TRUNCATE TABLE `pinjaman`;
TRUNCATE TABLE `produkoutlet`;
TRUNCATE TABLE `setoran`;
TRUNCATE TABLE `sirkulasibarang`;
TRUNCATE TABLE `sirkulasiayam`;
TRUNCATE TABLE `sirkulasiproduk`;
TRUNCATE TABLE `sirkulasibarangoutlet`;
TRUNCATE TABLE `sirkulasiayamoutlet`;
TRUNCATE TABLE `sirkulasiprodukoutlet`;
TRUNCATE TABLE `pemotongan`;
TRUNCATE TABLE `pemotongandetail`;
TRUNCATE TABLE `produksigudang`;
TRUNCATE TABLE `produksioutlet`;
TRUNCATE TABLE `produkoutlet`;
TRUNCATE TABLE `ayamoutlet`;
TRUNCATE TABLE `barangoutlet`;
UPDATE `produk` SET stock = 0;
UPDATE `ayam` SET pcs = 0, kg = 0;
UPDATE `baranggudang` SET stock = 0;
UPDATE `debitur` SET saldo = 0;